//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edzesterv_Osszeallito_Business_Desktop_Client.Models.Generals
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMIValuesMasterData
    {
        public System.Guid ID { get; set; }
        public decimal BMILowerIntervalValue { get; set; }
        public decimal BMIUpperIntervalValue { get; set; }
        public string Name { get; set; }
    }
}
