//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edzesterv_Osszeallito_Business_Desktop_Client.Models.Generals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingsTrainingPlan
    {
        public System.Guid TrainingsTrainingPlansID { get; set; }
        public System.Guid TrainingID { get; set; }
        public long Quantity { get; set; }
        public System.Guid TrainingPlanID { get; set; }
        public System.Guid UnitAmountMasterDataID { get; set; }
        public int BurnCaloriesPerUnitAmounts { get; set; }
        public System.Guid UserID { get; set; }
        public short DayOfWeek { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyingDate { get; set; }
    
        public virtual TrainingPlan TrainingPlan { get; set; }
        public virtual Training Training { get; set; }
        public virtual UnitAmountsMasterData UnitAmountsMasterData { get; set; }
    }
}
