//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edzesterv_Osszeallito_Business_Desktop_Client.Models.Generals
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingPlanBusinessEntities : DbContext
    {
        public TrainingPlanBusinessEntities()
            : base("name=TrainingPlanBusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BMIValuesMasterData> BMIValuesMasterDatas { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientsDiet> ClientsDiets { get; set; }
        public virtual DbSet<ClientsTrainingPlan> ClientsTrainingPlans { get; set; }
        public virtual DbSet<Diet> Diets { get; set; }
        public virtual DbSet<DietsMeal> DietsMeals { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<MuscleGroupsMasterData> MuscleGroupsMasterDatas { get; set; }
        public virtual DbSet<TrainingPlan> TrainingPlans { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<TrainingsMuscleGroup> TrainingsMuscleGroups { get; set; }
        public virtual DbSet<TrainingsTrainingPlan> TrainingsTrainingPlans { get; set; }
        public virtual DbSet<UnitAmountsMasterData> UnitAmountsMasterDatas { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersClient> UsersClients { get; set; }
        public virtual DbSet<UsersDiet> UsersDiets { get; set; }
        public virtual DbSet<UsersTrainingPlan> UsersTrainingPlans { get; set; }
    }
}
