//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edzesterv_Osszeallito_Business_Desktop_Client.Models.Generals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingsMuscleGroup
    {
        public System.Guid ID { get; set; }
        public System.Guid TrainingID { get; set; }
        public System.Guid MuscleGroupID { get; set; }
    
        public virtual MuscleGroupsMasterData MuscleGroupsMasterData { get; set; }
        public virtual Training Training { get; set; }
    }
}
